//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserDetail
    {
        public int UserId { get; set; }
        [Required(ErrorMessage = "Kullanýcý Adý Boþ Geçilemez!"), StringLength(20, ErrorMessage = "Kullanýcý Adý 20 karakterden fazla olamaz!")]
        public string UserName { get; set; }
        [Required(ErrorMessage="Parola Boþ Geçilemez!")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Parola Boþ Geçilemez!"),Compare("Password",ErrorMessage="Parolalar Uyuþmuyor!")]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Ad Boþ Geçilemez!")]
        public string FirsName { get; set; }
        [Required(ErrorMessage = "Soyad Boþ Geçilemez!")]
        public string Surname { get; set; }
        [Required(ErrorMessage = "Email Boþ Geçilemez!"),EmailAddress(ErrorMessage="Geçerli Bir Mail Yazýnýz!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Adres Boþ Geçilemez!")]
        public string Address { get; set; }
    }
}
